# Generated by Django 5.0.6 on 2024-05-25 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_id',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
